version: "3.2"
services:
    rabbit:
      image: rabbitmq:3-management-alpine
      hostname: rabbit
      ports:
      - "15672:15672"
      - "5672:5672"
      expose:
      - "15672"
      - "5672"

    app:
      build: .
      ports:
       - "8080:8080"
      depends_on:
      - "rabbit"
